### ISSUE TITLE
Cannot use phiremock when xdebug is running

### ISSUE THREAD

**Issue by wallsfantasy** [mcustiel/phiremock-codeception-extension#1]
Hi!,

When I run tests without xdebug phiremock runs fine, but when I enable xdebug I receive error

>  [GuzzleHttp\Exception\ConnectException] cURL error 7: Failed to connect to 127.0.0.1 port 18080: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  

The error occur only in the case that make request to phiremock.

**Comment by mcustiel** [comment]
Hi, I run phiremock with xdebug enabled for the projects where I use it. Could you try changing the port number in config or checking if that port is accepting connections? Also you can try to make it listen on interface 0.0.0.0

**Comment by wallsfantasy** [comment]
Thank you so much for reply.

I tried 0.0.0.0 without success. My vagrant box doesn't has firewall installed and currently I use default address/port (most configurations commented out).

The box is Ubuntu 15.10 running PHP 5.5.9 and Symfony 2.8 here is my configurations

codeception.yml
>
    extensions:
        enabled:
            - \Codeception\Extension\Phiremock
        config:
            \Codeception\Extension\Phiremock:
                #listen: 0.0.0.0:18080
                bin_path: bin
                #debug: true
                #startDelay: 1

api.suite.yml
>
    enabled:
        - ...
        - Phiremock:
            #host: 127.0.0.1
            #port: 18080

config_test.yml
>
    a_url: 'http://127.0.0.1:8086/a/'
    b_url: 'http://127.0.0.1:8086/b/'
    c_url: 'http://127.0.0.1:8086/c/'

xdebug.ini
>
    zend_extension=xdebug.so
    xdebug.remote_enable=1
    xdebug.remote_connect_back=1
    xdebug.remote_host=192.168.56.1

**Comment by mcustiel** [comment]
The `connection refused` thing makes me think that phiremock is not running, could you please check if your phiremock log has some error info?

**Comment by wallsfantasy** [comment]
That's correct. phiremock produces no log in freshly cleared phiremock.log compared to running without xdebug.

with xdebug enabled
>
vagrant@brick:/var/www/html/project$ tail -100 ./tests/_output/phiremock.log 
(blank line)

xdebug disabled
>
vagrant@brick:/var/www/html/project$ tail -100 ./tests/_output/phiremock.log 
[2016-08-04 17:52:20] stdoutLogger.INFO: Starting Phiremock... [] []
[2016-08-04 17:52:20] stdoutLogger.INFO: Phiremock http server listening on 0.0.0.0:8086 [] []
[2016-08-04 17:52:21] stdoutLogger.INFO: Request received: POST: http://localhost/email/customer/job || {"...(json)..."} [] []
[2016-08-04 17:52:21] stdoutLogger.INFO: Stopping Phiremock... [] []
[2016-08-04 17:52:21] stdoutLogger.INFO: Bye bye [] []
[2016-08-04 17:52:21] stdoutLogger.INFO: Stopping Phiremock... [] []
[2016-08-04 17:52:21] stdoutLogger.INFO: Bye bye [] []

**Comment by mcustiel** [comment]
Maybe running phiremock (vendor/bin/phiremock) manually witn -d parameter could help you know why it does not start.

**Comment by wallsfantasy** [comment]
Seems I can fire up phiremock while xdebug enabled with `./bin/phiremock -d` (I use Symfony 2.8 and already chmod x+a phiremock).

>
vagrant@brick:/var/www/html/ubq-marketing$ ./vendor/mcustiel/phiremock/bin/phiremock -d
[2016-08-04 19:29:13] stdoutLogger.INFO: Starting Phiremock in debug mode... [] []
[2016-08-04 19:29:13] stdoutLogger.DEBUG: Phiremock's expectation dir: /home/vagrant/.phiremock/expectations [] []
[2016-08-04 19:29:13] stdoutLogger.DEBUG: Registering shutdown function [] []
[2016-08-04 19:29:13] stdoutLogger.DEBUG: PCNTL present: Installing signal handlers [] []
[2016-08-04 19:29:13] stdoutLogger.INFO: Phiremock http server listening on 0.0.0.0:8086 [] []

Am I understand you correct?

**Comment by mcustiel** [comment]
So, phiremock runs... I have to say this is a very difficult issue to figure out.
My guess here, since the ports possibility was discarded, is that there is some problem with the forking of the phiremock process when using symfony process. Maybe running codeception in debug mode can give you some insights, but unfortunatelly I am not able to reproduce it locally.

**Comment by mcustiel** [comment]
Also it can be a versioning problem between symfony/process 3.1 (required by this extension) and your symfony2.8 installation. Try to use in your composer phiremock-codeception-extension: dev-master, I changed there the requirement for symfony process to this: "symfony/process": "^3.1|^2.7.15"

**Comment by wallsfantasy** [comment]
@mcustiel thanks for your replies. Let me finish my work on hand so I can try different packages.

**Comment by wallsfantasy** [comment]
@mcustiel Hi, sorry for delay.
I just required phiremock-codeception-extension:dev-master seems symfony/process version is pinned due to sensio/distribution-bundle require symfony/process:~2.2 . I'll let you know if I find something useful :(

**Comment by mcustiel** [comment]
Hi. If it works with some older symfony/process version I can change the composer schema.

**Comment by amkoro** [comment]
I faced the similar issue.

After some debug I found that this issue was caused by race - Phiremock server was not able to start properly and POST request to set expectations was failed (connection refused). Issue does not appear when your expectations setup goes not in a first test, so this is the reason why it can't be reproduced everywhere.

Solution is set a delay before tests will run:
startDelay: 1

**Comment by gitis** [comment]
I face the same issue. Using phiremock without **xdebug** enabled works well, however 
`[GuzzleHttp\Exception\ConnectException] cURL error 7: Failed to connect to 127.0.0.1 port 18080: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`
is thrown when **xdebug** is on.

Setting startDelay to 1 or higher doesn't seem to help.

> "codeception/codeception": "2.3.8"
> "symfony/symfony": "3.4.4"
> "guzzlehttp/guzzle": "6.2.3"

phiremock.log is empty.
