### ISSUE TITLE
SIGTERM and SIGKILL constants breaking docker environment

### ISSUE THREAD

**Issue by albert-prv** [mcustiel/phiremock-codeception-extension#11]
Hi,

When I using your extension in a docker container, I get this error:

`[PHPUnit_Framework_Exception]
  Use of undefined constant SIGTERM - assumed 'SIGTERM'`

Kind regards

**Comment by mcustiel** [comment]
Hi.
Please install pcntl extension in your container.

**Comment by mcustiel** [comment]
Added a check for installation of pcntl in version v1.3.1
