### ISSUE TITLE
\Codeception\Extension\PhiremockProcess::isPcntlEnabled always returns false and triggers warning

### ISSUE THREAD

**Issue by dewa1t** [mcustiel/phiremock-codeception-extension#12]
A part of the issue is reported in https://github.com/mcustiel/phiremock-codeception-extension/issues/11

When PCNTL extention is not enabled warning is triggered and Codeception tests are failed with:
```
[PHPUnit\Framework\Exception (8)]                      
Use of undefined constant SIGTERM - assumed 'SIGTERM'
```

When PCNTL extention is enabled, function \Codeception\Extension\PhiremockProcess::isPcntlEnabled returns `false`, because value `15` is provided for constant check here:

```
    private function isPcntlEnabled()
    {
        return !$this->isWindows() && defined(SIGTERM);
    }
```

`defined` expects constant name as a string in argument, and in the way it used it uses the constant value or triggers warning.

I'll provide PR soon, it fixes warning if PCNTL is disabled and allows to return correct value if PCNTL is enabled.

**Comment by mcustiel** [comment]
Fixed by @dewa1t 
Thank you very much.
