### ISSUE TITLE
symfony/process version jump

### ISSUE THREAD

**Issue by stefankleff** [mcustiel/phiremock-codeception-extension#21]
Hey! 
First of all thank you for your library! It's really useful!
But sadly I run into trouble, because you dropped support for symfony/process 2.x in the v1.4.1 patch release. I'm not sure which part of the process component is required to deal with the PNCTL correctly, but maybe you know if there is a chance to get support for 2.x

**Comment by mcustiel** [comment]
Hey, thank you for using it :)
Sure, have you checked in your local environment if the code still works OK when using 2.x? If it does, we can add it again in composer.json

**Comment by stefankleff** [comment]
I'll try that out as soon as possible.

**Comment by mcustiel** [comment]
Fixed in version v1.5.1. 
Thanks for your patience.
