### ISSUE TITLE
Configuration example is not working

### ISSUE THREAD

**Issue by niksamokhvalov** [mcustiel/phiremock-codeception-extension#22]
Hi! Thanks for extension and Phiremock.

Example of configuration from README is not working:

```
extensions:
    enabled:
        - \Codeception\Extension\Phiremock
    config:
        \Codeception\Extension\Phiremock:
            listen: 127.0.0.1:18080 # defaults to 0.0.0.0:8086
            bin_path: ../vendor/bin # defaults to codeception_dir/../vendor/bin 
            logs_path: /var/log/my_app/tests/logs # defaults to codeception's tests output dir
            debug: true # defaults to false
            startDelay: 1 # default to 0
            expectations_path: /my/expectations/path
```

Not worked with relative paths (`../vendor/bin`), only the absolute: `/app/vendor/bin`.

My versions:

* CentOS Linux release 7.3.1611 (Core).
* mcustiel/phiremock-codeception-extension 1.3.1.
* mcustiel/phiremock 1.4.0.

**Comment by mcustiel** [comment]
Hi @niksamokhvalov Thanks for reporting it.
As soon as I have some time I will have a look at it.

**Comment by niksamokhvalov** [comment]
Oh, really. I have two `codeception.yml` files, and I have indicated paths relative to the second (nested), however need relative to the first. Thanks!
