### ISSUE TITLE
Since #24, phiremock isn't killed at the end of the tests

### ISSUE THREAD

**Issue by michaelarnauts** [mcustiel/phiremock-codeception-extension#25]
Since this change, our instance of phiremock isnt' killed at the end of the tests, and the codeception process keeps on running.

When i revert that line, it starts working again.

https://github.com/mcustiel/phiremock-codeception-extension/pull/24/files#diff-b4d4128226e082c82a37ebba1c294ae9L96

**Comment by mcustiel** [comment]
Could you check if for you it works ok after upgrading to 1.5.2?

**Comment by michaelarnauts** [comment]
It seems packagist isn't updated yet...

**Comment by michaelarnauts** [comment]
I've manually modified the file in my vendor dir and the test is closed fine now. 
I'm not sure why this works, since when I took a quick look at Symfony/Process, it seems that it also accept arrays, so I wasn't sure if the implode was needed.

**Comment by mcustiel** [comment]
@michaelarnauts Thanks for checking. The implode is to support symfony version 2.

**Comment by michaelarnauts** [comment]
Okay, but that means that `symfony/process` v3.4.3 doesn't add the `exec` when a array is supplied?

**Comment by mcustiel** [comment]
Yes. But symfony/process v2x does not support array argument.

**Comment by mcustiel** [comment]
Fixed in version 1.5.2
