### ISSUE TITLE
Double path normalization for expectations path

### ISSUE THREAD

**Issue by smsalisbury** [mcustiel/phiremock-codeception-extension#29]
It seems that on Windows the expectations path is normalized twice: once in `\Codeception\Extension\Phiremock` (using php's `realpath`) and once in `mcustiel/bin/phiremock.php` (using `\Mcustiel\Phiremock\Common\Utils\FileSystem::getRealPath()`). This causes an `expectations_path` configuration of `tests/_data/phiremock` to add the current working directory twice. The debug log shows:

```
stdoutLogger.DEBUG: Phiremock's expectation dir: <working directory>/<working directory>/tests/_data/phiremock [] []
```

Changing line 82 of `src/Extension/Phiremock.php` fixes it for me

```
// from
$this->config['expectations_path'] ? realpath($this->config['expectations_path']) : null

// to
$this->config['expectations_path']
```

but I'm not familiar enough with how it works on other platforms to say if that'll cause issues on other filesystem types.

**Comment by mcustiel** [comment]
You are right. This should be done only on server side. Will fix it, thanks.

**Comment by mcustiel** [comment]
Fixed in version 2
