### ISSUE TITLE
How to configure multiple services

### ISSUE THREAD

**Issue by badams** [mcustiel/phiremock-codeception-extension#30]
Hi,

Is it possible to mock multiple external services with this extension? It seems you can only specify one host

**Comment by mcustiel** [comment]
Hello.
What I use to do in this case is to prefix the service I want to mock with a path in my config file:
for instance in my production config file I have:
```
'api1' => "server1.com",
'api2' => "server2.com"
```
and in my test config file:
```
'api1' => PHIREMOCK_URL . "/api1"
'api2' => PHIREMOCK_URL . "/api2"
```
