### ISSUE TITLE
Phiremock and SOAP

### ISSUE THREAD

**Issue by Danielavw** [mcustiel/phiremock-codeception-extension#34]
Hi Mariano

Do you know if phiremock's codeception extension work with standard protocol SOAP ? I checked that works fine with REST, but I am confused about methods from request part, seems quite focused for REST...

Thanks in advance!

**Comment by mcustiel** [comment]
Hello @Danielavw 
I think it depends on your SOAP implementation, if it goes over http it should be perfectly fine to use it with phiremock.
