### ISSUE TITLE
PHP 8 & phiremock-codeception-extension 2.1.1: Module Phiremock could not be found and loaded 

### ISSUE THREAD

**Issue by linslin** [mcustiel/phiremock-codeception-extension#46]
Hey m8,

I currently try to update my project to PHP 8 and your phiremock codeception version 2.1.x. My setup is fully available here: https://github.com/linslin/Yii2-Curl/tree/develop - It gives me this error on my windows machine.

```
In ModuleContainer.php line 117:
Module Phiremock could not be found and loaded              
```

Any idea? Do you see some mistake in my setup? Thanks

-> Failing build: https://travis-ci.org/github/linslin/Yii2-Curl/builds/759744733

**Comment by linslin** [comment]
Never mind: https://github.com/mcustiel/phiremock-codeception-module was just missing. Thanks

**Comment by linslin** [comment]
Hm, could you take a look on it? https://travis-ci.org/github/linslin/Yii2-Curl/jobs/759745799 Stucking

**Comment by mcustiel** [comment]
Hello @linslin 
What I see in your codeception.yml file is that phiremock seems to be enabled only for the unit suite. Then it's not running for the acceptance suite. Maybe that's the reason for the error in your CI job.

**Comment by linslin** [comment]
@mcustiel thanks for your feedback. I've added all suites but the error still comes up.

This is the latest build: https://travis-ci.org/github/linslin/Yii2-Curl/jobs/759747815 and this is the configuration file: https://github.com/linslin/Yii2-Curl/blob/develop/codeception.yml 

Any idea?

**Comment by mcustiel** [comment]
Please check this config: 
```
 bin_path: ../vendor/bin # defaults to codeception_dir/../vendor/bin
```
If I am not wrong, because of where your codeception.yml file is located it should be `vendor/bin` (the full path can be seen here in the logs and it also seems to point in that direction: `Running exec /home/travis/build/linslin/Yii2-Curl/../vendor/bin/phiremock -i 127.0.0.1 -p 18080 -d > /home/travis/build/linslin/Yii2-Curl/tests/_output//phiremock.log 2>&1`). 
It is possible for you to run the tests locally? Maybe that could help you to check the log files.

**Comment by linslin** [comment]
I've changed the path. Its the same path now like in the master branch: https://github.com/linslin/Yii2-Curl/blob/master/codeception.yml which passed https://travis-ci.org/github/linslin/Yii2-Curl/builds/757369484.

The path seems fine now: 

`Running exec /home/travis/build/linslin/Yii2-Curl/vendor/bin/phiremock -i 127.0.0.1 -p 18080 -d > /home/travis/build/linslin/Yii2-Curl/tests/_output//phiremock.log 2>&1` but the build is still broken: https://travis-ci.org/github/linslin/Yii2-Curl/jobs/759748350

This also happens on my local machine. You could try to checkout the develop branch to reproduce this error.

**Comment by linslin** [comment]
Uhm, I was able to fix it .... the base package was missing in my composer file and the other packages seems to have no requirements for this package. Thats why it was not working. Idk if there is a hard conjunction on **phiremock-codeception-extension** and **phiremock-codeception-module**. If so, its maybe a good idea to add the requirement to them.

`"mcustiel/phiremock": "^2.1",`

**Comment by mcustiel** [comment]
Yes, I downloaded your develop branch and the error was that the `phiremock-server` dependency is missing in composer.json.
It is not hard-integrated into the extension anymore because there's people which uses docker or the phar and don't need the composer dependency at all.
Please check the readme, there's details there on how to set it up. 
I am glad that you could solve the problem.

**Comment by mcustiel** [comment]
Now that you're using v2, it would be nice to have some feedback from you since your were using version 1 for a long time and have enough experience to compare. That would help me a lot.  Thanks.

**Comment by linslin** [comment]
The integration to v2 was easy. There is no upgrade guide but I was able to modifiy my project based on your main documentation. I hit the missing package error because the base package "mcustiel/phiremock" was part of the requirement in v1 but was removed in v2. Thats why this error came up and I had no idea how to fix it because I just didnt saw that the base package requirement was removed. (May take a look at the v1 composer file)

Everything else was good. I also liked the depecration warnings.

**Comment by mcustiel** [comment]
Awesome, thank you very much.
You have a point regarding the upgrade guide. Will create one as soon as I have some free time.

**Comment by linslin** [comment]
-> https://travis-ci.org/github/linslin/Yii2-Curl/jobs/759749382

**Comment by OlegMuron** [comment]
Hi!

Sorry, about that in the closed thread - but I have the same issue, after upgrading my project to PHP 8.1 and `mcustiel/phiremock-codeception-extension` from 1.9.0 to 2.2.2. 

My composer requeire section is:
```
  "require": {
    "php": ">=8.1",
    "aws/aws-sdk-php": "3.222.15",
    "codeception/c3": "^2.4",
    "codeception/codeception": "^4.1",
    "codeception/module-asserts": "^1.3",
    "codeception/module-db": "^1.0",
    "codeception/module-phpbrowser": "^1.0",
    "codeception/module-redis": "^1.0",
    "codeception/module-rest": "^1.2",
    "doctrine/annotations": "^1.13",
    "fakerphp/faker": "~1.19",
    "flow/jsonpath": "^0.3.4",
    "guzzlehttp/guzzle": "^7.4.0",
    "mcustiel/phiremock": "^2.0",
    "mcustiel/phiremock-codeception-extension": "^2.0",
    "mockery/mockery": "^1.0",
    "nesbot/carbon": "^2.0",
    "phpmd/phpmd": "^2.6",
    "predis/predis": "^1.1",
    "sebastian/phpcpd": "^6.0",
    "squizlabs/php_codesniffer": "^3.4",
    "stecman/symfony-console-completion": "^0.11",
    "symfony/process": "^6.0",
    "vlucas/phpdotenv": "^5.0"
  },

```

My suite.yml extensions config is:
```
extensions:
    enabled:
        - \Codeception\Extension\Phiremock
    config:
        \Codeception\Extension\Phiremock:
            listen: 127.0.0.1:18080 # defaults to 0.0.0.0:8086
            bin_path: vendor/bin # defaults to codeception_dir/../vendor/bin
            logs_path: _output # defaults to codeception's tests output dir
            debug: true # defaults to false
            startDelay: 1 # default to 0
```

And when I try to tun test, I receive:
```
In ModuleContainer.php line 118:
  Module Phiremock could not be found and loaded  
```

If anything - the Phiremock extension is installed and present in the autoloader list :( 

Maybe you have any idea what it could be related to? Thank you!
