### ISSUE TITLE
Start phiremock instance performance

### ISSUE THREAD

**Issue by m1ndgr3p** [mcustiel/phiremock-codeception-extension#49]
Hi there!

We are using this extension in our project and it's greate! thanks for your work.

If we use option `wait_until_ready` we are waiting for 1 second in any case. I propose to decrease this value to about 100 microseconds or make this value not hardcoded but configurable. what do you think? We have tons of functional tests and with this improvement we can speed up our ci/cd pipelines.

**Comment by mcustiel** [comment]
@m1ndgr3p Thank you very much for your nice words and sorry for the wait. Please check the PR to see if that's the feature you're expecting.
