### ISSUE TITLE
Support SF 6 / Codeception 5

### ISSUE THREAD

**Issue by fivetide** [mcustiel/phiremock-codeception-extension#51]
Hey, SF 6 has been out for a while, and Codeception 5 is in pre-release state right now. Do you plan on supporting those?

**Comment by darkmatus** [comment]
This would be fine :+1:

**Comment by mcustiel** [comment]
Hello @fivetide  @darkmatus 
Changed sf version constrain to composer.json 
Codeception5 is still not released as stable, will wait for it.
