### ISSUE TITLE
Can I disable mocking?

### ISSUE THREAD

**Issue by chudarek** [mcustiel/phiremock-codeception-extension#7]
Hey, first let me thank you for PhireMock Extension!

I have one question. Is it possible to disable mocking? I'm testing API by creating mock, but as soon as real API will be ready to use I would love to disable mock and runnning test against real API. The only idea I have is to create separated tests (one with PhireMock and one for real API - without Phiremock) with group annotation and then run tests for suite with group tag. I'm wondering if there is better solution for this.

Thank you.
Marek

**Comment by mcustiel** [comment]
Hey @chudarek, thank you for using it :)
The way you have to control when to use the mocks or not is through your application's config, by instance through having different configurations for different environments and you set the environment information in a file or env variable .
My suggestion would be to create two environments for your acceptance tests, like acceptance and smoke. Or acceptance_mocked and acceptance_not_mocked. And for one you point your application to the mocks and for the other to the real services.

Hope this helps you.
