### ISSUE TITLE
Coverage report

### ISSUE THREAD

**Issue by linslin** [mcustiel/phiremock-codeception-extension#8]
Have you yet tried to create a coverage report by using phiremock - https://github.com/Codeception/c3 + http://codeception.com/docs/11-Codecoverage right now? This should be go with an remote coverage report. 

Running `codecept run functional --coverage-html` works fine but results in 0% coverage.
Running `codecept run unit --coverage-html` works fine but results in 0% coverage.
Running `codecept run --coverage --coverage-html` &  `codecept run acceptance --coverage-html` fails with: 

> [PHPUnit_Framework_Exception]
> file_get_contents(http://localhost/myapp/c3/report/clear): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

-> this may will help us by including c3 as option https://github.com/Codeception/Codeception/issues/515

Lets talk about this. My public mail is info@linslin.org
Cheers

**Comment by mcustiel** [comment]
Hello @linslin,
As far as I know code coverage through c3 is part of codeception and the application being tested should take care of it, not the extensions. 
Could you please explain me what is your idea for this extension regarding c3?

Best,
Mariano.

**Comment by linslin** [comment]
I think  this is a speciall case because we need to debug remote + the webserver been destroyed after the teste were finished + c3 is unable to write the reports because the webserver rejects the access of:

- c3/report/clover
- c3/report/serialized
- c3/report/html
- c3/report/clear

**Comment by mcustiel** [comment]
I saw your code and I think it is not an issue with the extension, but how you configured your tests. 
C3 is needed when the code that you are covering is remote, but in your case it is local (Curl.php). What you have there is more a functional test than an acceptance test. My guess would be to move your test from acceptance to functional and modify your coverage config in codeception.yml so it has something like this:
```yaml
coverage:
    enabled: true
    include:
        - Curl.php
```
Then run codeception with the arguments needed for the local coverage.
This way your file will be included in the coverage report. Please tell me if it worked for you.
Best regards,
Mariano.

**Comment by linslin** [comment]
@mcustiel Thanks for your feedback. Yea, I know its a functional test. I read your documentation of phiremack carefully but I did not found an example how to implement it as a functional test. Could you guide me here?

**Comment by mcustiel** [comment]
I think it is already perfect as a functional tests. Just move it to functional folder instead of acceptance and change the actor to be FunctionalTester instead of Acceptance Tester. Then setup your functional.suite.yml as you did for acceptance.
I guess that should be enough.

**Comment by linslin** [comment]
Thanks, I'll check it and give you some feedback.

**Comment by mcustiel** [comment]
Added PR https://github.com/linslin/Yii2-Curl/pull/61

**Comment by linslin** [comment]
Thanks, works like a charm =)
